DROP TABLE IF EXISTS attempts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS exam_sessions;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS categories;
DROP EXTENSION IF EXISTS pg_trgm;
